Bump pytest-benchmark to 4.0.0
Due to avoid AttributeError: module 'py' has no attribute 'io'
Related issue: https://github.com/pytest-dev/pytest/issues/10420